stages:
    - test

test_with_mocha:
    stage: test
    script:
        - npm install
        - npm run unit -loglevel silent
        - npm run integration -loglevel silent
    tags:
        - node
        - mongodb
